// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-faq-guides.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/faq-data.ts
var GUIDE_INDEX_URL = "https://resuvibe.ai/guide-index.json";
var CACHE_TTL_MS = 12 * 60 * 60 * 1e3;
var cache = null;
var inflight = null;
async function loadIndex() {
  const now = Date.now();
  if (cache && now - cache.fetchedAt < CACHE_TTL_MS) return cache.data;
  if (inflight) return inflight;
  inflight = (async () => {
    const res = await fetch(GUIDE_INDEX_URL, { headers: { accept: "application/json" } });
    if (!res.ok) throw new Error(`Failed to load FAQ index: ${res.status}`);
    const data = await res.json();
    cache = { data, fetchedAt: Date.now() };
    return data;
  })();
  try {
    return await inflight;
  } finally {
    inflight = null;
  }
}
async function getAllGuides() {
  const idx = await loadIndex();
  return idx.guides ?? [];
}
async function getGuideBySlug(slug) {
  const idx = await loadIndex();
  if (idx.bySlug && idx.bySlug[slug]) return idx.bySlug[slug];
  return (idx.guides ?? []).find((g) => g.slug === slug);
}
function summarizeGuide(g) {
  return {
    slug: g.slug,
    title: g.title,
    category: g.category,
    description: g.description,
    url: `https://resuvibe.ai/FAQ/${g.slug}`
  };
}

// src/lib/mcp/tools/list-faq-guides.ts
var list_faq_guides_default = defineTool({
  name: "list_faq_guides",
  title: "List FAQ guides",
  description: "List every public FAQ / resume guide published on ResuVibe. Returns slug, title, category, short description, and canonical URL for each guide.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const items = (await getAllGuides()).map(summarizeGuide);
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { guides: items, count: items.length }
    };
  }
});

// src/lib/mcp/tools/get-faq-guide.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var get_faq_guide_default = defineTool2({
  name: "get_faq_guide",
  title: "Get FAQ guide",
  description: "Fetch the full contents of one public ResuVibe FAQ / resume guide by its slug. Returns title, category, canonical URL, and all section headings and HTML bodies.",
  inputSchema: {
    slug: z.string().min(1).describe("Guide slug, e.g. 'account-executive'. Use list_faq_guides to discover slugs.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const guide = await getGuideBySlug(slug);
    if (!guide) {
      return {
        content: [{ type: "text", text: `No FAQ guide found for slug '${slug}'.` }],
        isError: true
      };
    }
    const payload = {
      slug: guide.slug,
      title: guide.title,
      category: guide.category,
      description: guide.description,
      url: `https://resuvibe.ai/FAQ/${guide.slug}`,
      sections: guide.sections ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/search-faq.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var search_faq_default = defineTool3({
  name: "search_faq",
  title: "Search FAQ guides",
  description: "Case-insensitive substring search across ResuVibe's public FAQ / resume guides. Matches on title, slug, category, and description. Returns summaries; call get_faq_guide for full contents.",
  inputSchema: {
    query: z2.string().min(1).describe("Free-text search query.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query }) => {
    const q = query.toLowerCase();
    const all = await getAllGuides();
    const matches = all.filter((g) => {
      const hay = [g.slug, g.title, g.category ?? "", g.description ?? ""].join(" ").toLowerCase();
      return hay.includes(q);
    });
    const items = matches.map(summarizeGuide);
    return {
      content: [
        {
          type: "text",
          text: items.length === 0 ? `No FAQ guides matched '${query}'.` : JSON.stringify(items, null, 2)
        }
      ],
      structuredContent: { guides: items, count: items.length, query }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "resuvibe-faq-mcp",
  title: "ResuVibe FAQ",
  version: "0.1.0",
  instructions: "Read-only access to ResuVibe's public FAQ and resume-guide library (the same content published at https://resuvibe.ai/FAQ). Use list_faq_guides to discover topics, search_faq to find guides by keyword, and get_faq_guide to read the full text of one guide. No user account data, applications, resumes, cover letters, or interview data are available through this server.",
  tools: [list_faq_guides_default, get_faq_guide_default, search_faq_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
